### PR TITLE
xlayoutdisplay: remove unnecessary dependency on gtest

### PR DESCRIPTION
**Pull request by alex-courtis**

### CODE REVIEW

**Comment by rdnetto** [comment]
It's insufficient to just edit the ebuild - you also need to regenerate the checksum with `repoman manifest .` or `ebuild xlayoutdisplay-1.0.2.ebuild manifest`.

You could do this in a Docker container, or you could just tick the box to let me push changes to your branch. ;)

**Comment by alex-courtis** [comment]
Nice one!

Actually... I need to figure out how to depend on cmake 3.10... 3.9 doesn't have the gtest module that I use (facepalm)

EDIT: never mind... 3.10 doesn't yet exist... it will _soon_.

Sig updated via my gentoo install.

**Comment by rdnetto** [comment]
Cmake 3.10 definitely exists, just not on stable:
```
$ eix cmake
[U] dev-util/cmake
     Available versions:  3.9.6 (~)3.10.2 (~)3.10.3 (~)3.11.0 {doc emacs ncurses qt5 server system-jsoncpp test}
     Installed versions:  3.10.2(07:30:57 29/01/18)(ncurses server -doc -emacs -qt5 -system-jsoncpp -test)
     Homepage:            https://cmake.org/
     Description:         Cross platform Make
```

I've set the min cmake version, relevant docs are [here](https://devmanual.gentoo.org/eclass-reference/cmake-utils.eclass/index.html)

**Comment by alex-courtis** [comment]
Lawson - many thanks

**Pull request merged**
